// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationRestoran;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MigrationRestoran.Migrations
{
    [DbContext(typeof(RestorantContext))]
    [Migration("20200401172502_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MigrationRestoran.Abonent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("abonent");
                });

            modelBuilder.Entity("MigrationRestoran.ClientCards", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasColumnName("discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ClientCards");
                });

            modelBuilder.Entity("MigrationRestoran.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Bill")
                        .HasColumnName("bill")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Count")
                        .HasColumnName("count")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("ItemsId")
                        .HasColumnName("items_id")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("details");
                });

            modelBuilder.Entity("MigrationRestoran.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("MigrationRestoran.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AbonentId")
                        .HasColumnName("abonent_id")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Bill")
                        .HasColumnName("bill")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("EndOrder")
                        .HasColumnName("end_order")
                        .HasColumnType("datetime");

                    b.Property<int?>("SourceId")
                        .HasColumnName("source_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeOrder")
                        .HasColumnName("time_order")
                        .HasColumnType("datetime");

                    b.Property<int?>("WaiterId")
                        .HasColumnName("waiter_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3213E83E1B4D841E")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("TimeOrder");

                    b.ToTable("order");
                });

            modelBuilder.Entity("MigrationRestoran.Sources", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("sources");
                });

            modelBuilder.Entity("MigrationRestoran.Waiters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("waiters");
                });

            modelBuilder.Entity("MigrationRestoran.Details", b =>
                {
                    b.HasOne("MigrationRestoran.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_detail_ToOrder")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
